Update requirements.txt
Downgrade psycopg2-binary to 2.8.6, because of the issue

```
django.core.serializers.base.DeserializationError: Problem installing fixture '/home/app/publichealth.home.json': database connection isn't set to UTC: (wagtailcore.pagerevision:pk=1) field_value was '['oleg']'
```

More info: https://github.com/psycopg/psycopg2/issues/1293#issuecomment-862835147